### ISSUE TITLE
Docker actions are out of date

### ISSUE THREAD

**Issue by madisonjordan** [uclahs-cds/tool-Docker-action#3]
[docker login action](https://github.com/marketplace/actions/docker-login) 
v1 -> v2.1.0

[docker metadata action](https://github.com/marketplace/actions/docker-metadata-action)
v3 -> v4.1.1

[docker build action](https://github.com/marketplace/actions/build-and-push-docker-images)
v2 -> v3.2.0

---

I don't know if this actually improves (or breaks) anything we need but I noticed it while looking into a probably unrelated building issue I'm having right now. Which I'll post about if I can narrow down if it's the build settings or just how poorly I made my Dockerfile.

**Comment by nwiltsie** [comment]
I'm not sure when this was addressed, but we're currently on `v3`, `v5`, and `v5` respectively.
